manipulator_controller:
  type: position_controllers/JointTrajectoryController #effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
    joint2:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
    joint3:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
    joint4:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
    joint5:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
    joint6:
      p: 10
      d: 0.1
      i: 0.5
      i_clamp: 0.5
